server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: rol-service
              uri: http://rol-service:8081
              predicates:
                - Path=/api/roles/**
           
            - id: usuario-service
              uri: http://usuario-service:8082
              predicates:
                - Path=/api/usuarios/**
                
            - id: grado-service
              uri: http://grado-service:8083
              predicates:
                - Path=/api/grados/**
                
            - id: curso-service
              uri: http://curso-service:8084
              predicates:
                - Path=/api/cursos/**
                
            - id: materia-service
              uri: http://materia-service:8085
              predicates:
                - Path=/api/materias/**
                
            - id: actividad-service
              uri: http://actividad-service:8086
              predicates:
                - Path=/api/actividades/**
                
            - id: horario-service
              uri: http://horario-service:8087
              predicates:
                - Path=/api/horarios/**
                
            - id: nota-service
              uri: http://nota-service:8088
              predicates:
                - Path=/api/notas/**
                
            - id: asistencia-service
              uri: http://asistencia-service:8089
              predicates:
                - Path=/api/asistencias/**
                
            - id: matricula-service
              uri: http://matricula-service:8090
              predicates:
                - Path=/api/matriculas/**